// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Verificar se as variáveis de ambiente estão disponíveis ou usar valores fixos
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://dwhbznsijdsiwccamfvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3aGJ6bnNpamRzaXdjY2FtZnZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwNzUyMTEsImV4cCI6MjA3NTY1MTIxMX0.WhU7sghKmYJTARkulQmDId8obT_iCcI5xMHKdDdItjg";

// Verificação de segurança para garantir que as URLs e chaves estão presentes
if (!SUPABASE_URL) {
  console.error("ERRO: VITE_SUPABASE_URL não está definido no ambiente");
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error("ERRO: VITE_SUPABASE_ANON_KEY não está definido no ambiente");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
